const fs=require('fs'),vm=require('vm'),assert=require('assert');
const els={};const element=id=>els[id]??=( {innerHTML:'',textContent:'',value:id==='philoA'?'kant':id==='philoB'?'util':'',style:{},addEventListener(){},focus(){},classList:{toggle(){}},setAttribute(){},removeAttribute(){}} );
let exportBlob;const ctx={console,Blob,URL:{createObjectURL:b=>(exportBlob=b,'blob:test'),revokeObjectURL(){}},setTimeout:()=>0,clearTimeout(){},localStorage:{getItem:()=>null,setItem(){}},location:{hash:''},history:{replaceState(){}},document:{getElementById:element,querySelector:element,querySelectorAll:()=>[],body:{appendChild(){}},createElement:()=>({click(){},remove(){}})},window:{addEventListener(){},scrollTo(){},print(){}}};Object.assign(ctx,ctx.window);ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync('dist/data.js','utf8'),ctx);vm.runInContext(fs.readFileSync('dist/reader.js','utf8'),ctx);vm.runInContext(fs.readFileSync('dist/app.js','utf8'),ctx);
const D=ctx.window.TERROR;const routes=['start','lektuere','rollen','dilemma','recht','philosophie','simulation','film','politik','spiele','journal','quellen','lehrperson',...D.modules.map(m=>'lektuere/'+m.id),...D.roles.map(m=>'rollen/'+m.id),...D.dilemmas.map(m=>'dilemma/'+m.id),...D.videos.map(m=>'film/'+m.id),...D.politics.map(m=>'politik/'+m.id)];
for(const route of routes){ctx.location.hash='#'+route;vm.runInContext('render()',ctx);assert(els.main.innerHTML.includes('<h1>'),route);assert(!els.main.innerHTML.includes('undefined'),route);assert(!els.main.innerHTML.includes('Diese Station gibt es nicht.'),route);for(const [,link] of els.main.innerHTML.matchAll(/href="#([^"]+)"/g)){assert(routes.includes(link)||link==='main',route+' -> '+link);}}
for(const group of [D.modules,D.roles,D.dilemmas,D.videos,D.politics,D.philosophies])assert.equal(new Set(group.map(m=>m.id)).size,group.length);
for(const p of D.philosophies)assert(D.sources[p.source],p.id);
for(let i=0;i<=D.simStages.length;i++){vm.runInContext('state.sim.stage='+i+';simulation()',ctx);}
assert.throws(()=>vm.runInContext("validImport({format:'bad'})",ctx));assert.throws(()=>vm.runInContext("validImport({format:'terror-journal-v1',state:{notes:{a:{text:'x',label:'x',route:'javascript:alert(1)'}}}})",ctx));
assert.equal(vm.runInContext("parseTime('12:59')",ctx),779);assert(Number.isNaN(vm.runInContext("parseTime('12:70')",ctx)));
vm.runInContext("state.notes.test={label:'Test',text:'Text mit < & >',route:'start',updated:1};exportData('json')",ctx);
(async()=>{const exported=JSON.parse(await exportBlob.text());assert.equal(exported.state.notes.test.text,'Text mit < & >');assert.equal(exported.format,'terror-journal-v1');console.log(JSON.stringify({routesChecked:routes.length,simulationStages:8,contentReferences:'pass',invalidImport:'rejected',clipTimeValidation:'pass',jsonExport:'pass'}));})();

for(const s of D.scenes){assert(D.modules.some(m=>m.id===s.id));assert(s.end>s.start&&s.end<=5617.34);for(const p of s.parts||[]){assert(p.start>=s.start&&p.end<=s.end&&p.end>p.start);assert(p.page>=1&&p.page<=103);}}
ctx.location.hash='#lektuere/urteile';vm.runInContext('render();readerPart=1;render()',ctx);assert(els.main.innerHTML.includes('Urteilsfassung: Freispruch'));assert.equal(vm.runInContext('readerScene("urteile").page',ctx),91);
